### ISSUE TITLE
Code redundancy issues in Structures.cs

### ISSUE THREAD

**Issue by swsabean** [michael-mayes/capturedpackets#1]
With reference to Revision 260, in the file PacketCaptureAnalyser\Analysis\Latency Analysis\Structures.cs,we have the following implementation of the override of the Equals method of the PacketCaptureAnalyser.Analysis.LatencyAnalysis.Structures.DictionaryKey structure.

public override bool Equals(object obj)
{
    if (obj is DictionaryKey)
    {
        DictionaryKey key = (DictionaryKey)obj;

```
    // The two dictionary keys are deemed identical if the fields of each are identical
    return
        this.HostId == key.HostId &&
        this.IsReliable == key.IsReliable &&
        this.SequenceNumber == key.SequenceNumber;
}
else
{
    return false;
}
```

}

DictionaryKey is a structure, and therefore a value type. By default, when the Object.Equals method of a value type is called, it returns true if the fields are identical, false otherwise. There is no check to see if the are the same instance because they are value types.

Thus the above override accomplishes the same thing as the default Equals method and could therefore be eliminated. The same is true of == and !=. The same is also true of the DictionaryValue structure. 

Hope this helps.

**Comment by michael-mayes** [comment]
Thank you for your suggestion. I will take a look shortly. All suggestions more than welcome!

**Comment by michael-mayes** [comment]
I've done a bit of reading up on this

The addition of these methods was made as part of original implementation of the change from using data table to dictionaries, which offered up significant performance benefits

Additionally it address two instances of a warning from FxCop for the CA1815 rule

The CA1815 rule was added by Microsoft for performance purposes

This is the description of that rule on [MSDN](https://msdn.microsoft.com/en-us/library/ms182276.aspx):

> For value types, the inherited implementation of Equals uses the Reflection library, and compares the contents of all fields. Reflection is computationally expensive, and comparing every field for equality might be unnecessary. If you expect users to compare or sort instances, or use them as hash table keys, your value type should implement Equals. If your programming language supports operator overloading, you should also provide an implementation of the equality and inequality operators.

So this change is valid and was added for correct reasons

Closing as no issue in this case

Further suggestions welcomed
